/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum ArmingState {
  Disarmed = 'Disarmed',
  Arming = 'Arming',
  Armed = 'Armed',
  Unknown = 'Unknown'
}

export declare export declare function bootstrapVehicleStatus(): VehicleStatus

/** Provide richer error context for the renderer. */
export declare export declare function describeStatusChannel(): string

export declare export declare function healthCheck(): StatusMessage

export declare export declare function runDiagnostics(timeoutMs?: number | undefined | null): Promise<StatusMessage>

export declare export declare function simulateFailure(): void

/** Message returned to the Electron shell. */
export interface StatusMessage {
  kind: string
  message: string
}

export interface VehicleStatus {
  vehicleId: string
  vehicleType: VehicleType
  armingState: ArmingState
  heartbeatMillis: number
}

export declare const enum VehicleType {
  Multirotor = 'Multirotor',
  FixedWing = 'FixedWing',
  VTOL = 'VTOL',
  Rover = 'Rover',
  Sub = 'Sub',
  Unknown = 'Unknown'
}

export declare export declare function version(): string
