/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum ArmingState {
  Disarmed = 'Disarmed',
  Arming = 'Arming',
  Armed = 'Armed',
  Unknown = 'Unknown'
}

export interface BatteryStatus {
  voltageV: number
  currentA?: number
  remainingPercent?: number
}

export declare export declare function bootstrapVehicleStatus(): VehicleStatus

export declare export declare function cachedMissionPlan(): MissionPlan

export declare export declare function cachedParameters(): Array<ParameterValue>

export declare const enum ConnectionPhase {
  Idle = 'Idle',
  Discovering = 'Discovering',
  Connecting = 'Connecting',
  Connected = 'Connected',
  Disconnecting = 'Disconnecting',
  Disconnected = 'Disconnected',
  Error = 'Error'
}

export interface ConnectionStatus {
  phase: ConnectionPhase
  message?: string
  device?: DeviceDescriptor
}

export declare export declare function connectMavlink(options?: ConnectOptions | undefined | null): Promise<ConnectionStatus>

export interface ConnectOptions {
  link?: LinkKind
  deviceId?: string
  serialPath?: string
  serialBaud?: number
  udpBind?: string
  udpTargetHost?: string
  udpTargetPort?: number
  label?: string
  forceSimulated?: boolean
}

export declare export declare function currentConnectionStatus(): ConnectionStatus

export declare export declare function currentMissionPlan(): MissionPlan

export declare export declare function describeStatusChannel(): string

export interface DeviceDescriptor {
  id: string
  label: string
  transport: LinkKind
  serialPath?: string
  manufacturer?: string
  product?: string
  vid?: number
  pid?: number
  udpBind?: string
  udpTargetHost?: string
  udpTargetPort?: number
}

export declare export declare function disconnectMavlink(): Promise<void>

export declare export declare function downloadMission(timeoutMs?: number | undefined | null): Promise<MissionPlan>

export declare export declare function fetchParameters(timeoutMs?: number | undefined | null): Promise<Array<ParameterValue>>

export interface FlightModeStatus {
  label: string
  baseMode: number
  customMode: number
}

export declare const enum GpsFixType {
  NoFix = 'NoFix',
  DeadReckoning = 'DeadReckoning',
  Fix2D = 'Fix2D',
  Fix3D = 'Fix3D',
  DGps = 'DGps',
  RtkFloat = 'RtkFloat',
  RtkFixed = 'RtkFixed',
  StaticHold = 'StaticHold',
  Other = 'Other'
}

export interface GpsStatus {
  fixType: GpsFixType
  satellitesVisible: number
  latitudeDeg?: number
  longitudeDeg?: number
  altitudeM?: number
  hdop?: number
  vdop?: number
}

export declare export declare function healthCheck(): StatusMessage

export declare const enum LinkKind {
  Simulated = 'Simulated',
  Serial = 'Serial',
  Udp = 'Udp'
}

export declare export declare function listDevices(): Array<DeviceDescriptor>

export interface MissionCoordinate {
  latitudeDeg: number
  longitudeDeg: number
  altitudeM: number
}

export declare const enum MissionFrame {
  Global = 'Global',
  GlobalRelativeAlt = 'GlobalRelativeAlt',
  GlobalTerrainAlt = 'GlobalTerrainAlt',
  Mission = 'Mission'
}

export interface MissionItem {
  seq: number
  command: number
  frame: MissionFrame
  latitudeDeg: number
  longitudeDeg: number
  altitudeM: number
  param1: number
  param2: number
  param3: number
  param4: number
  autoContinue: boolean
  isCurrent: boolean
}

export declare const enum MissionOperationKind {
  Upload = 'Upload',
  Download = 'Download'
}

export interface MissionOperationReport {
  operation: MissionOperationKind
  status: MissionOperationStatus
  message?: string
  revision: number
}

export declare const enum MissionOperationStatus {
  Success = 'Success',
  Failed = 'Failed',
  Cancelled = 'Cancelled'
}

export interface MissionPlan {
  planId: string
  revision: number
  items: Array<MissionItem>
  home?: MissionCoordinate
  lastModifiedMillis: number
  notes?: string
}

export declare const enum MissionSyncStage {
  Idle = 'Idle',
  Downloading = 'Downloading',
  Uploading = 'Uploading',
  AwaitingAck = 'AwaitingAck',
  Completed = 'Completed',
  Failed = 'Failed'
}

export interface MissionSyncStatus {
  stage: MissionSyncStage
  index?: number
  total?: number
  message?: string
}

export interface ParameterValue {
  name: string
  value: number
  paramType: string
  index?: number
}

export declare export declare function registerEventSink(callback: (...args: any[]) => any): void

export declare export declare function runDiagnostics(timeoutMs?: number | undefined | null): Promise<StatusMessage>

export declare export declare function simulateFailure(): void

export declare export declare function startDeviceWatch(intervalMs?: number | undefined | null): Promise<void>

/** Message returned to the Electron shell. */
export interface StatusMessage {
  kind: string
  message: string
}

export declare export declare function uploadMission(plan: MissionPlan, timeoutMs?: number | undefined | null): Promise<MissionPlan>

export interface VehicleStatus {
  vehicleId: string
  vehicleType: VehicleType
  armingState: ArmingState
  heartbeatMillis: number
  flightMode?: FlightModeStatus
  battery?: BatteryStatus
  gps?: GpsStatus
}

export declare const enum VehicleType {
  Multirotor = 'Multirotor',
  FixedWing = 'FixedWing',
  VTOL = 'VTOL',
  Rover = 'Rover',
  Sub = 'Sub',
  Unknown = 'Unknown'
}

export declare export declare function version(): string
